### ISSUE TITLE
JuliaQuantum description

### ISSUE THREAD

**Issue by Travis-S** [CQuIC-GitHub/CQuIC-GitHub.github.io#11]
On `develop` branch, I added JuliaQuantum project to list of things we are working on. But I did not know exactly how to describe it. Could you take a look and add a good explanation?

**Comment by i2000s** [comment]
Updated on demand at https://github.com/CQuIC-GitHub/CQuIC-GitHub.github.io/commit/511e14e69b6c68cf40a581a492c2e9548cd73d16   :-)
